version: "3.0"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=development_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - "127.0.0.1:5432:5432/tcp"