version: "3.0"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "127.0.0.1:5432:5432/tcp"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 127.0.0.1:5555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.test
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id